name: Build & Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      HUGO_CACHEDIR: ".hugo_cache"

    steps:
      # 1. Check out the source code
      - uses: actions/checkout@v4

      # 2. Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # 3. Build the site into `public/`
      - name: Build
        run: hugo --minify

      # 4. Deploy to the gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
